Repository MariiaBel/msu-library, pull requests merged in 2024-09, with the labels that each got.

#21 71605263-feat: implement 2 state for filter panel
  .storybook/main.js
  .storybook/preview.js
  src/01_app/styles/variables.scss
  src/04_features/filter/index.html
  src/04_features/filter/ui/filter.html
  src/04_features/filter/ui/filter.scss
  src/06_shared/img/svg/chevron-down.svg
  src/06_shared/img/svg/chevron-up.svg
  src/06_shared/ui/button/button-accent.html
  src/06_shared/ui/button/button.html
  src/06_shared/ui/button/button.scss
  src/06_shared/ui/checkbox/checkbox-accent.html
  src/06_shared/ui/checkbox/checkbox.scss
  src/index.html
  src/index.scss
  src/stories/Checkbox.js
  src/stories/Filter.stories.js
  src/stories/SvgIcons.mdx
  src/stories/filter.js
  src/stories/main.js
Labels: ready to codereview

#16 feat: add light button
  .gitignore
  src/01_app/styles/variables.scss
  src/04_features/filter/ui/filter.scss
  src/06_shared/ui/button/button.html
  src/06_shared/ui/button/button.scss
  src/index.html
  src/stories/Button.js
  src/stories/Button.stories.js
  src/stories/Checkbox.js
  src/stories/button.css
  src/stories/search.js
Labels: ready to codereview

#22 74243517-feat:adds header and header sb
  src/01_app/layout/icons-import.html
  src/01_app/styles/extends.scss
  src/01_app/styles/global.scss
  src/03_widgets/header/header.html
  src/03_widgets/header/header.scss
  src/04_features/search/ui/search.html
  src/04_features/search/ui/search.scss
  src/06_shared/img/svg/logo.svg
  src/index.scss
  src/stories/Header.stories.js
  src/stories/header.js
Labels: ready to merge

#25 test:78120055-add dark theme to storybook
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/01_app/styles/extends.scss
  src/01_app/styles/global.scss
  src/04_features/search/ui/search.scss
  src/stories/Checkbox.js
  src/stories/SvgIcons.mdx
  src/stories/filter.js
  src/stories/header.js
  src/stories/search.js
Labels: ready to codereview

#30 fix: deleted the build.yml file
  .github/build.yml
  .github/workflows/build.yml
  vite.config.mjs
Labels: fixes needed
